### ISSUE TITLE
Square brackets should be allowed in frame headers

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/cif_api#24]
cif_api flags square brackets in frame headers as errors, although this is legal according to the CIF2 publication. For example

```
#\#_CIF2.0
data_with[1]
_item1 hello
```
produces

```
Parsing block_char_check.dic ...
  Error code 105 at line 2, column 10, near "":
    required whitespace separation was missing
  Error code 105 at line 2, column 9, near "":
    required whitespace separation was missing
  Error code 134 at line 2, column 10, near "[":
    unexpected data value
  3 errors.
```

**Comment by jcbollinger** [comment]
I initially had trouble reproducing this, until I recognized that there is a typo in the CIF version header in the example input above.  The CIF API will therefore interpret that file according to CIF 1.1, in which mode it accepts the input without complaint.  The following variant, however, is (wrongly) rejected by the CIF API's parser:

```
#\#CIF_2.0
data_with[1]
_item1 hello
```
